{{- if .Values.deployment.volumes -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "compose.fullname" . }}
  labels: {{ include "compose.labels" . | nindent 4 }}
spec:
  {{- if .Values.deployment.storageClassName -}}
  storageClassName: {{ .Values.deployment.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.deployment.pvSize | default "4Gi" }}
{{- end }}
