{{- if .Values.deployment.volumes -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "compose.fullname" . }}
spec:
  storageClassName: {{ .Values.deployment.volumes.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.deployment.pvSize | default "4Gi" }}
{{- end }}
